#!/bin/bash

DB_USER=$1

if [ -z "$DB_USER" ]; then
    echo "Usage: $0 <DB_USER>"
    exit 1
fi

SECRET_NAME="mongodb_${DB_USER}"
SECRET=$(get_or_create_secret ${SECRET_NAME})

if [ $? -eq 0 ]; then
    echo "${DB_USER}:${SECRET}"
else
    echo "Failed to get or create Admin Secret"
    exit 1
fi
